"""initial schema

Revision ID: 878069d5befa
Revises: 
Create Date: 2026-06-14 14:49:53.772032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '878069d5befa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('email_codes',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('plans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price_cny_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('activation_codes',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('activation_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activation_codes_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activation_codes_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activation_codes_used_by'), ['used_by'], unique=False)

    op.create_table('cloud_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('remind_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('sub_tasks', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('tapd_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tapd_work_item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cloud_todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cloud_todos_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_todos_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_todos_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_todos_user_id'), ['user_id'], unique=False)

    op.create_table('device_sync_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_pulled', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'device_id')
    )
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identities_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_provider_uid'), ['provider_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trial_until', sa.DateTime(), nullable=True),
    sa.Column('paid_until', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('days_added', sa.Integer(), nullable=False),
    sa.Column('paid_until_before', sa.DateTime(), nullable=True),
    sa.Column('paid_until_after', sa.DateTime(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['activation_codes.code'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redemptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redemptions_user_id'))

    op.drop_table('redemptions')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    op.drop_table('subscriptions')
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_identities_provider_uid'))
        batch_op.drop_index(batch_op.f('ix_identities_provider'))

    op.drop_table('identities')
    op.drop_table('device_sync_state')
    with op.batch_alter_table('cloud_todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cloud_todos_user_id'))
        batch_op.drop_index(batch_op.f('ix_cloud_todos_updated_at'))
        batch_op.drop_index(batch_op.f('ix_cloud_todos_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_cloud_todos_client_uuid'))

    op.drop_table('cloud_todos')
    with op.batch_alter_table('activation_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activation_codes_used_by'))
        batch_op.drop_index(batch_op.f('ix_activation_codes_plan_id'))
        batch_op.drop_index(batch_op.f('ix_activation_codes_batch_id'))

    op.drop_table('activation_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('email_codes')
    op.drop_table('app_config')
    # ### end Alembic commands ###
